// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace AITraing
{
    public partial class MLModel1
    {
        public const string RetrainFilePath =  @"P:\3-level\coding\ibovs\datasets\train.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader);
        }



        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }


        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"battery_power", @"battery_power"),new InputOutputColumnPair(@"blue", @"blue"),new InputOutputColumnPair(@"clock_speed", @"clock_speed"),new InputOutputColumnPair(@"dual_sim", @"dual_sim"),new InputOutputColumnPair(@"fc", @"fc"),new InputOutputColumnPair(@"four_g", @"four_g"),new InputOutputColumnPair(@"int_memory", @"int_memory"),new InputOutputColumnPair(@"m_dep", @"m_dep"),new InputOutputColumnPair(@"mobile_wt", @"mobile_wt"),new InputOutputColumnPair(@"n_cores", @"n_cores"),new InputOutputColumnPair(@"pc", @"pc"),new InputOutputColumnPair(@"px_height", @"px_height"),new InputOutputColumnPair(@"px_width", @"px_width"),new InputOutputColumnPair(@"ram", @"ram"),new InputOutputColumnPair(@"sc_h", @"sc_h"),new InputOutputColumnPair(@"sc_w", @"sc_w"),new InputOutputColumnPair(@"talk_time", @"talk_time"),new InputOutputColumnPair(@"three_g", @"three_g"),new InputOutputColumnPair(@"touch_screen", @"touch_screen"),new InputOutputColumnPair(@"wifi", @"wifi")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"battery_power",@"blue",@"clock_speed",@"dual_sim",@"fc",@"four_g",@"int_memory",@"m_dep",@"mobile_wt",@"n_cores",@"pc",@"px_height",@"px_width",@"ram",@"sc_h",@"sc_w",@"talk_time",@"three_g",@"touch_screen",@"wifi"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=4,NumberOfLeaves=4,FeatureFraction=1F,LabelColumnName=@"price_range",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
 }
