// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AITraing
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"battery_power")]
            public float Battery_power { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"blue")]
            public float Blue { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"clock_speed")]
            public float Clock_speed { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"dual_sim")]
            public float Dual_sim { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"fc")]
            public float Fc { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"four_g")]
            public float Four_g { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"int_memory")]
            public float Int_memory { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"m_dep")]
            public float M_dep { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"mobile_wt")]
            public float Mobile_wt { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"n_cores")]
            public float N_cores { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"pc")]
            public float Pc { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"px_height")]
            public float Px_height { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"px_width")]
            public float Px_width { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"ram")]
            public float Ram { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"sc_h")]
            public float Sc_h { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"sc_w")]
            public float Sc_w { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"talk_time")]
            public float Talk_time { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"three_g")]
            public float Three_g { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"touch_screen")]
            public float Touch_screen { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"wifi")]
            public float Wifi { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"price_range")]
            public float Price_range { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"battery_power")]
            public float Battery_power { get; set; }

            [ColumnName(@"blue")]
            public float Blue { get; set; }

            [ColumnName(@"clock_speed")]
            public float Clock_speed { get; set; }

            [ColumnName(@"dual_sim")]
            public float Dual_sim { get; set; }

            [ColumnName(@"fc")]
            public float Fc { get; set; }

            [ColumnName(@"four_g")]
            public float Four_g { get; set; }

            [ColumnName(@"int_memory")]
            public float Int_memory { get; set; }

            [ColumnName(@"m_dep")]
            public float M_dep { get; set; }

            [ColumnName(@"mobile_wt")]
            public float Mobile_wt { get; set; }

            [ColumnName(@"n_cores")]
            public float N_cores { get; set; }

            [ColumnName(@"pc")]
            public float Pc { get; set; }

            [ColumnName(@"px_height")]
            public float Px_height { get; set; }

            [ColumnName(@"px_width")]
            public float Px_width { get; set; }

            [ColumnName(@"ram")]
            public float Ram { get; set; }

            [ColumnName(@"sc_h")]
            public float Sc_h { get; set; }

            [ColumnName(@"sc_w")]
            public float Sc_w { get; set; }

            [ColumnName(@"talk_time")]
            public float Talk_time { get; set; }

            [ColumnName(@"three_g")]
            public float Three_g { get; set; }

            [ColumnName(@"touch_screen")]
            public float Touch_screen { get; set; }

            [ColumnName(@"wifi")]
            public float Wifi { get; set; }

            [ColumnName(@"price_range")]
            public float Price_range { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
